# ==============================================================================
# AI DISCLAIMER
# This script was programmatically generated by Antigravity, an AI assistant.
# ==============================================================================

import struct
import sys

def validate_gff(filepath):
    try:
        with open(filepath, 'rb') as f:
            data = f.read()
        
        if len(data) < 56:
            print(f"{filepath}: Too short to be a valid GFF (size: {len(data)} bytes)")
            return False
            
        sig = data[0:4]
        ver = data[4:8]
        
        print(f"File: {filepath}")
        print(f"  Signature: {sig}")
        print(f"  Version: {ver}")
        
        if sig not in (b'BIC ', b'GFF '):
            print(f"  WARNING: Unexpected signature {sig}")
            
        struct_offset, struct_count = struct.unpack('<II', data[8:16])
        field_offset, field_count = struct.unpack('<II', data[16:24])
        label_offset, label_count = struct.unpack('<II', data[24:32])
        data_offset, data_count = struct.unpack('<II', data[32:40])
        field_indices_offset, field_indices_count = struct.unpack('<II', data[40:48])
        list_indices_offset, list_indices_count = struct.unpack('<II', data[48:56])
        
        print(f"  Structs: offset {struct_offset}, count {struct_count}")
        print(f"  Fields: offset {field_offset}, count {field_count}")
        print(f"  Labels: offset {label_offset}, count {label_count}")
        print(f"  Data: offset {data_offset}, count {data_count}")
        print(f"  Field Indices: offset {field_indices_offset}, count {field_indices_count}")
        print(f"  List Indices: offset {list_indices_offset}, count {list_indices_count}")
        
        # Check if offsets and sizes match file size
        expected_size = max(
            struct_offset + struct_count * 12,
            field_offset + field_count * 12,
            label_offset + label_count * 16,
            data_offset + data_count,
            field_indices_offset + field_indices_count,
            list_indices_offset + list_indices_count
        )
        print(f"  Actual file size: {len(data)} bytes")
        print(f"  Expected min size based on offsets: {expected_size} bytes")
        
        if len(data) < expected_size:
            print("  ERROR: File is truncated or has invalid offsets")
            return False
            
        print("  GFF structural check PASSED.")
        return True
    except Exception as e:
        print(f"  ERROR parsing file: {e}")
        return False

if __name__ == "__main__":
    validate_gff("servervault/uxkgk6wk/daniel.bic")
    validate_gff("servervault/uxkgk6wk/neil.bic")
