# ==============================================================================
# AI DISCLAIMER
# This script was programmatically generated by Antigravity, an AI assistant.
# ==============================================================================

import struct
import sys

def read_gff_name(filepath):
    try:
        with open(filepath, 'rb') as f:
            data = f.read()
        
        sig = data[0:4]
        struct_offset, struct_count = struct.unpack('<II', data[8:16])
        field_offset, field_count = struct.unpack('<II', data[16:24])
        label_offset, label_count = struct.unpack('<II', data[24:32])
        data_offset, data_count = struct.unpack('<II', data[32:40])
        
        # Read Label Table
        labels = []
        for i in range(label_count):
            start = label_offset + i * 16
            label_bytes = data[start:start+16]
            label_str = label_bytes.split(b'\x00')[0].decode('utf-8', errors='ignore')
            labels.append(label_str)
            
        first_name_label_idx = None
        last_name_label_idx = None
        for idx, label in enumerate(labels):
            if label == "FirstName":
                first_name_label_idx = idx
            elif label == "LastName":
                last_name_label_idx = idx
                
        if first_name_label_idx is None or last_name_label_idx is None:
            print(f"{filepath}: Could not find FirstName or LastName labels.")
            return
            
        def read_loc_string(offset):
            # Size (uint32)
            size = struct.unpack('<I', data[data_offset + offset : data_offset + offset + 4])[0]
            # LocString structure inside the data block starts at data_offset + offset + 4
            str_block = data[data_offset + offset + 4 : data_offset + offset + 4 + size]
            # StringRef (int32)
            # StringCount (uint32)
            string_ref, string_count = struct.unpack('<iI', str_block[0:8])
            if string_count > 0:
                # LanguageID (int32)
                # StringLength (uint32)
                lang_id, string_len = struct.unpack('<ii', str_block[8:16])
                string_data = str_block[16:16+string_len].decode('utf-8', errors='ignore')
                return string_data
            return ""

        first_name = ""
        last_name = ""
        for i in range(field_count):
            f_start = field_offset + i * 12
            f_type, f_label_idx, f_val_or_offset = struct.unpack('<III', data[f_start:f_start+12])
            if f_type == 12: # CEXOLOCSTRING
                if f_label_idx == first_name_label_idx:
                    first_name = read_loc_string(f_val_or_offset)
                elif f_label_idx == last_name_label_idx:
                    last_name = read_loc_string(f_val_or_offset)
                    
        print(f"File: {filepath}")
        print(f"  Name: '{first_name}' '{last_name}'")
    except Exception as e:
        print(f"Error reading {filepath}: {e}")

if __name__ == "__main__":
    read_gff_name("servervault/uxkgk6wk/daniel.bic")
    read_gff_name("servervault/uxkgk6wk/neil.bic")
